package lib

import (
	"bytes"
	"fmt"

	"github.com/hashicorp/hcl/hcl/printer"
	jsonParser "github.com/hashicorp/hcl/json/parser"
)

func ToHCL(j string) (string, error) {
	input := j
	var err error
	if err != nil {
		return "", fmt.Errorf("unable to read from stdin: %s", err)
	}

	ast, err := jsonParser.Parse([]byte(input))
	if err != nil {
		return "", fmt.Errorf("unable to parse JSON: %s", err)
	}

	var buff []byte
	buffer := bytes.NewBuffer(buff)
	buffer.WriteString("#GENERATED BY TERRAYAML\n")
	err = printer.Fprint(buffer, ast)
	if err != nil {
		return "", fmt.Errorf("unable to print HCL: %s", err)
	}

	return string(buffer.Bytes()), nil
}
